### ISSUE TITLE
Schau mal hier

### ISSUE THREAD

**Issue by frederikheld** [anoff/docker-compose-influxdb-grafana#1]
Schau mal hier
https://github.com/frederikheld/pot-pourri/tree/master/services/persistence
und hier
https://github.com/frederikheld/pot-pourri/tree/master/services/visualization

Das Docker Networking Setup und die passende telegraf.conf dazu fand ich etwas knifflig. Bei mir ist es aber auch deswegen ein klein wenig komplizierter, weil telegraf/influxdb und grafana in verschiedenen services liegen, weil ich Grafana nicht in jedem Kontext starten will.

**Comment by anoff** [comment]
Habs "plain" ohne vordefinierte Configs gemacht 😁
